# /etc/calamares/modules/bootloader.conf
---
efiBootLoader: "systemd-boot"

efiBootloaderId: "Veles"
kernel: "/boot/vmlinuz"
img: "/boot/initrd"
timeout: "5"

# Parametry przekazywane do jądra przy starcie
kernelParams: [ "quiet", "splash", "rw" ]
# kernelLine: ", with _manjaro_kernel_"
# fallbackKernelLine: ", with _manjaro_kernel_ (fallback initramfs)"