# /etc/calamares/modules/bootloader.conf
---
efiBootloader: "systemd-boot"

efiBootloaderId: "Veles"
kernel: "/boot/vmlinuz"
img: "/boot/initrd"
timeout: "5"

# Parametry przekazywane do jądra przy starcie
kernelParams: [ "quiet", "splash", "rw" ]