---
# /etc/calamares/modules/keyboard.conf

vconsoleConfigFile: "/etc/vconsole.conf"
writeVConsoleConfig: true

# Opcjonalnie: wyłączenie automatycznego dopasowania z kbd-model-map
convertedKeymap: "/usr/share/kbd/keymaps/xkb"

useLocale1: true
