# /etc/calamares/modules/users.conf

setRootPassword: false

defaultShell: /bin/zsh
allowWeakPasswords: true
initialId: 1000
userRequiredGroups:
    - video
    - audio
    - power
    - wheel
    - input

user:
  shell: /bin/zsh
  forbidden_names: [ root ]
  home_permissions: "o700"